[package]
name = "player"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.33"
dialoguer = "0.10"
rodio = "0.15"
walkdir = "2.3"
crossterm = "0.25"
parking_lot = "0.12"

[profile.release]
debug = false
lto = true
opt-level = 3